# Generated by Django 5.2.8 on 2025-11-11 22:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('dui', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Parámetros El Salvador', max_length=100)),
                ('isss_empleado_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('isss_techo', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('afp_empleado_pct', models.DecimalField(decimal_places=2, default=Decimal('7.25'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hasta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuota_fija', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tasa_exceso_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='appfinanciero.product')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinanciero.employee')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='appfinanciero.payrollperiod')),
            ],
            options={
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
