# Generated by Django 5.2.8 on 2025-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanciero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(default='TEMP', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(default='unid', max_length=20),
        ),
    ]
